Bump Android NuGet dependencies versions
Kebechet/Maui.RevenueCat.InAppBilling pull request #44
Opened 2024-10-10 23:43 UTC by MoienTajik

**Why?**
There are some other NuGet packages out there (In my case, `Plugin.MauiMTAdmob`) which has indirect dependency on `Xamarin.AndroidX.Fragment` version >= 1.8.3. This causes version conflict issue with `Maui.RevenueCat.InAppBilling` as the version here is lower.

2024-10-11 06:37 UTC, Kebechet commented
Hello @MoienTajik 
thanks for the PR, in following days I will take a look. 
I experienced the same incompatibility issue with the exact package in the past so we will 100% merge this if there are no side-effects.

2024-10-14 09:26 UTC, Kebechet requested changes
I have tested this and it seems correctly.
After you resolve those CR changes I will merge this PR and publish it.

2024-10-14 09:26 UTC, Kebechet commented on src/Maui.RevenueCat.Android/Maui.RevenueCat.Android.csproj
> +		<Version>7.13.0.0</Version>
version is derived from the native Android library used. V`7.12.0`.
So please change it as `7.12.0.1` where 4th number is the number of patch for this version

2024-10-14 09:26 UTC, Kebechet commented on src/Maui.RevenueCat.InAppBilling/Maui.RevenueCat.csproj
>    </ItemGroup>
again 7.12.0.1

2024-10-14 09:26 UTC, Kebechet commented on src/Maui.RevenueCat.InAppBilling/Maui.RevenueCat.csproj
>      <PackageReleaseNotes>Removed redundant files causing long-path error</PackageReleaseNotes>
please adjust this description as well

2024-10-14 09:26 UTC, Kebechet commented on src/Maui.RevenueCat.Android/Maui.RevenueCat.Android.csproj
>  		<PackageReleaseNotes>Bumped to newer RC version</PackageReleaseNotes>
please adjust this description

2024-10-14 13:22 UTC, MoienTajik commented
Done @Kebechet

2024-10-14 14:54 UTC, merged

2024-10-14 15:18 UTC, Kebechet commented
Both
[Android](https://www.nuget.org/packages/Kebechet.Maui.RevenueCat.Android/7.12.0.1) and [InAppBilling](https://www.nuget.org/packages/Kebechet.Maui.RevenueCat.InAppBilling/4.5.3) nugets are released. 
Thank you for the contribution! ❤️

2024-10-15 07:18 UTC, MoienTajik commented
Awesome! Thanks.